### PR TITLE
availability.html and availability.css

### PR DESCRIPTION
**Pull request by tushargoyal22**
---

**What's this PR do? (related issue if exists)**
I have only added availability.html and avail.css file. Rest kept unchanged .If something otherthan this is changed , i would make commit once again by deleting the folder and cloning again and adding the avail.html and avail.css file again.

**Any context you want to provide on the implementation?**
I have spent a very large time make stylish toggle button just by css:

**Screenshots? (necessary if an UI/UX change)**

### CODE REVIEW

**Comment by tushargoyal22** [comment]
Kindly check the toggle button specially xD

**Comment by abhigyank** [comment]
@b18030  I am unable to see your changes due to the merge conflicts. 
I had already merged the first two commits in the previous PR you don't need to add them to the PR again. 
Only `availabilty status html and css` commit should be a part of this PR. Can you fix that and update?

**Comment by tushargoyal22** [comment]
How to fix this problem sir .I also thought there would be some problem.To do this should i remove folder from machine and clone latest and add availability status and html in it

**Comment by tushargoyal22** [comment]
I added avail.css and availability.html

**Pull request closed without merging**
